https://docs.google.com/spreadsheets/d/1xgvrXE4YBku-ouB4CXbURnqeo7IfRBZUaLxzRW1W82E/edit?gid=0#gid=0

In [1]:
import pandas as pd

# Rodzaj danych 1

```
nazwa źródła danych,link,rodzaj danych
mapa stacji informacje ogólne,,"tabele html, wykresy, tekst"
```

In [2]:
url_path_1 = "https://powietrze.gios.gov.pl/pjp/content/measuring_air_assessment_measurings"

In [3]:
df_list = pd.read_html(url_path_1)  #  , header=0

In [4]:
df_liczba_stanowisk_pomiarowych = df_list[0]

In [5]:
df_liczba_stanowisk_pomiarowych

,Unnamed: 0,Typ pomiaru: automatyczny,Typ pomiaru: manualny,ÅÄ cznie w województwie
0,DOLNOÅLÄSKIE,79,83,162
1,KUJAWSKO-POMORSKIE,108,61,169
2,LUBELSKIE,32,34,66
3,LUBUSKIE,49,50,99
4,ÅÓDZKIE,59,47,106
5,MAÅOPOLSKIE,93,68,161
6,MAZOWIECKIE,103,47,150
7,OPOLSKIE,38,24,62
8,PODLASKIE,39,24,63
9,PODKARPACKIE,62,47,109
10,POMORSKIE,69,27,96
11,ÅWIÄTOKRZYSKIE,47,29,76
12,ÅLÄSKIE,113,87,200
13,WARMIÅSKO-MAZURSKIE,42,61,103
14,WIELKOPOLSKIE,49,37,86
15,ZACHODNIOPOMORSKIE,40,34,74

## Czyszczenie tablicy

In [6]:
df_liczba_stanowisk_pomiarowych_copy = df_liczba_stanowisk_pomiarowych.copy()  #  Tworzenie kopii data frame
new_columns = list(df_liczba_stanowisk_pomiarowych_copy.iloc[0, 1:])  #  nazwy kolumn pochodzą z 1 wiersza
df_liczba_stanowisk_pomiarowych_copy = df_liczba_stanowisk_pomiarowych_copy.iloc[1:, :]  #  usuwam 1 wiersz
df_liczba_stanowisk_pomiarowych_copy.columns = ['Wojedództwo'] + new_columns  #  ustawiam nowe nazwy kolumn

In [7]:
df_liczba_stanowisk_pomiarowych_copy

             Wojedództwo   79  83  162
1     KUJAWSKO-POMORSKIE  108  61  169
2              LUBELSKIE   32  34   66
3               LUBUSKIE   49  50   99
4               ÅÓDZKIE   59  47  106
5           MAÅOPOLSKIE   93  68  161
6            MAZOWIECKIE  103  47  150
7               OPOLSKIE   38  24   62
8              PODLASKIE   39  24   63
9           PODKARPACKIE   62  47  109
10             POMORSKIE   69  27   96
11      ÅWIÄTOKRZYSKIE   47  29   76
12             ÅLÄSKIE  113  87  200
13  WARMIÅSKO-MAZURSKIE   42  61  103
14         WIELKOPOLSKIE   49  37   86
15    ZACHODNIOPOMORSKIE   40  34   74

In [8]:
df_list[1]

,Unnamed: 0,"PM2,5 stanowiska manualne","PM2,5 stanowiska automatyczne",PM10 stanowiska automatyczne,PM10 stanowiska manualne
0,ZACHODNIOPOMORSKIE,4,4,6,8
1,WIELKOPOLSKIE,3,4,10,10
2,WARMIÅSKO-MAZURSKIE,5,4,6,9
3,ÅWIÄTOKRZYSKIE,2,6,10,9
4,ÅLÄSKIE,8,8,21,13
5,POMORSKIE,1,9,11,7
6,PODLASKIE,2,7,7,4
7,PODKARPACKIE,1,12,15,14
8,OPOLSKIE,2,3,9,4
9,MAZOWIECKIE,4,16,17,13
10,MAÅOPOLSKIE,6,3,25,22
11,ÅÓDZKIE,3,5,10,17
12,LUBUSKIE,3,5,8,10
13,LUBELSKIE,3,3,6,10
14,KUJAWSKO-POMORSKIE,5,6,11,11
15,DOLNOÅLÄSKIE,5,6,13,16

In [9]:
df_liczba_stanowisk_podzial = df_list[1]
df_liczba_stanowisk_podzial_copy = df_liczba_stanowisk_podzial.copy()
new_columns = list(df_liczba_stanowisk_podzial_copy.iloc[0, 1:])
df_liczba_stanowisk_podzial_copy = df_liczba_stanowisk_podzial_copy.iloc[1:, :]
df_liczba_stanowisk_podzial_copy.columns = ['Wojedództwo'] + new_columns
df_liczba_stanowisk_podzial_copy

             Wojedództwo  4   4   6   8
1          WIELKOPOLSKIE  3   4  10  10
2   WARMIÅSKO-MAZURSKIE  5   4   6   9
3       ÅWIÄTOKRZYSKIE  2   6  10   9
4              ÅLÄSKIE  8   8  21  13
5              POMORSKIE  1   9  11   7
6              PODLASKIE  2   7   7   4
7           PODKARPACKIE  1  12  15  14
8               OPOLSKIE  2   3   9   4
9            MAZOWIECKIE  4  16  17  13
10          MAÅOPOLSKIE  6   3  25  22
11              ÅÓDZKIE  3   5  10  17
12              LUBUSKIE  3   5   8  10
13             LUBELSKIE  3   3   6  10
14    KUJAWSKO-POMORSKIE  5   6  11  11
15        DOLNOÅLÄSKIE  5   6  13  16

# Rodzaj danych 2

In [10]:
url_path_2 = "https://powietrze.gios.gov.pl/pjp/archives"

In [11]:
url_path_2_1 = "https://powietrze.gios.gov.pl/pjp/archives/downloadFile/223"

In [12]:
import requests

In [13]:
responce = requests.get(url_path_2_1)

In [14]:
with open('dane.zip', 'wb') as f:
    f.write(responce.content)  #  to jest plik zip: responce.content

In [15]:
!unzip dane.zip

Archive:  dane.zip
  inflating: 2000_NO2_1g.xlsx
  inflating: 2000_NO2_24g.xlsx
  inflating: 2000_NOx_1g.xlsx
  inflating: 2000_O3_1g.xlsx
  inflating: 2000_PM10_24g.xlsx
  inflating: 2000_SO2_24g.xlsx

In [16]:
df_dict = pd.read_excel("2000_NO2_1g.xlsx", sheet_name=None)

In [17]:
for key in df_dict.keys():
  print(key)

2000_NO2_1g

In [18]:
df = df_dict['2000_NO2_1g']

## Czyszczenie danych

In [19]:
df_no2_1g = df.copy()

### Usuwam wiersze bez danych pomiarowych

In [20]:
df_no2_1g = df_no2_1g.iloc[2:, :]

In [21]:
df_no2_1g.rename(columns={'Kod stacji': 'Czas'}, inplace=True)

### Dostosowuje typy danych

In [22]:
df_no2_1g.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 2 to 8785
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Czas                  8784 non-null   object
 1   DsCzer02              8395 non-null   object
 2   DsJelw05              8461 non-null   object
 3   MpKrakowWIOSAKra6117  7415 non-null   object
 4   MpKrakowWIOSBulw6118  6457 non-null   object
 5   MpKrakowWIOSPrad6115  3865 non-null   object
 6   MzBelskIGFPAN         7923 non-null   object
 7   Pm.a01a               8716 non-null   object
 8   Pm.a02a               8202 non-null   object
 9   Pm.a03a               8715 non-null   object
 10  Pm.a04a               8563 non-null   object
 11  Pm.a06a               8631 non-null   object
 12  Pm.a07a               8472 non-null   object
 13  Pm.a08a               8640 non-null   object
 14  Pm.a09a               8425 non-null   object
 15  SlBytomByto_modrz     8191 non-null   object
 16  SlSosnoSosn_narut     8607 non-null   object
 17  WpKonin311009D009102  4870 non-null   object
dtypes: object(18)
memory usage: 1.2+ MB

In [23]:
for col in df_no2_1g.loc[:, 'DsCzer02':'WpKonin311009D009102'].columns:
    df_no2_1g[col] = df_no2_1g[col].astype(float)

In [ ]:
df_no2_1g.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 2 to 8785
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Czas                  8784 non-null   object
 1   DsCzer02              8395 non-null   float64
 2   DsJelw05              8461 non-null   float64
 3   MpKrakowWIOSAKra6117  7415 non-null   float64
 4   MpKrakowWIOSBulw6118  6457 non-null   float64
 5   MpKrakowWIOSPrad6115  3865 non-null   float64
 6   MzBelskIGFPAN         7923 non-null   float64
 7   Pm.a01a               8716 non-null   float64
 8   Pm.a02a               8202 non-null   float64
 9   Pm.a03a               8715 non-null   float64
 10  Pm.a04a               8563 non-null   float64
 11  Pm.a06a               8631 non-null   float64
 12  Pm.a07a               8472 non-null   float64
 13  Pm.a08a               8640 non-null   float64
 14  Pm.a09a               8425 non-null   float64
 15  SlBytomByto_modrz     8191 non-null   float64
 16  SlSosnoSosn_narut     8607 non-null   float64
 17  WpKonin311009D009102  4870 non-null   float64
dtypes: float64(17), object(1)
memory usage: 1.2+ MB

In [24]:
df_no2_1g['Czas'] = pd.to_datetime(df_no2_1g['Czas'])

In [ ]:
df_no2_1g.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 2 to 8785
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Czas                  8784 non-null   datetime64[ns]
 1   DsCzer02              8395 non-null   float64
 2   DsJelw05              8461 non-null   float64
 3   MpKrakowWIOSAKra6117  7415 non-null   float64
 4   MpKrakowWIOSBulw6118  6457 non-null   float64
 5   MpKrakowWIOSPrad6115  3865 non-null   float64
 6   MzBelskIGFPAN         7923 non-null   float64
 7   Pm.a01a               8716 non-null   float64
 8   Pm.a02a               8202 non-null   float64
 9   Pm.a03a               8715 non-null   float64
 10  Pm.a04a               8563 non-null   float64
 11  Pm.a06a               8631 non-null   float64
 12  Pm.a07a               8472 non-null   float64
 13  Pm.a08a               8640 non-null   float64
 14  Pm.a09a               8425 non-null   float64
 15  SlBytomByto_modrz     8191 non-null   float64
 16  SlSosnoSosn_narut     8607 non-null   float64
 17  WpKonin311009D009102  4870 non-null   float64
dtypes: datetime64[ns](1), float64(17)
memory usage: 1.2 MB

In [25]:
df_no2_1g.describe()

,Czas,DsCzer02,DsJelw05,MpKrakowWIOSAKra6117,MpKrakowWIOSBulw6118,MpKrakowWIOSPrad6115,MzBelskIGFPAN,Pm.a01a,Pm.a02a,Pm.a03a,Pm.a04a,Pm.a06a,Pm.a07a,Pm.a08a,Pm.a09a,SlBytomByto_modrz,SlSosnoSosn_narut,WpKonin311009D009102
count,8784,8395.000000,8461.000000,7415.000000,6457.000000,3865.000000,7923.000000,8716.000000,8202.000000,8715.000000,8563.000000,8631.000000,8472.000000,8640.000000,8425.000000,8191.000000,8607.000000,4870.000000
mean,2000-07-02 00:30:00,6.607147,14.425009,73.485233,31.692117,29.219405,8.737726,25.355553,15.832480,13.526334,14.022656,13.742208,14.343012,18.045718,12.601662,24.600171,39.720344,7.370431
min,2000-01-01 01:00:00,0.000000,0.000000,1.000000,3.000000,2.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,7.000000,2.000000
25%,2000-04-01 12:45:00,4.000000,8.000000,50.000000,19.000000,17.000000,4.000000,14.000000,7.000000,7.000000,6.000000,7.000000,8.000000,10.000000,6.000000,15.000000,27.000000,5.000000
50%,2000-07-02 00:30:00,6.000000,12.000000,70.000000,29.000000,26.000000,7.000000,22.000000,13.000000,12.000000,10.000000,11.000000,12.000000,15.000000,10.000000,22.000000,38.000000,6.000000
75%,2000-10-01 12:15:00,8.000000,19.000000,94.000000,42.000000,38.000000,12.000000,32.000000,21.000000,17.000000,19.000000,18.000000,18.000000,24.000000,17.000000,32.000000,50.000000,9.000000
max,2001-01-01 00:00:00,41.000000,76.000000,245.000000,117.000000,109.000000,43.000000,129.000000,168.000000,68.000000,79.000000,114.000000,72.000000,110.000000,65.000000,114.000000,121.000000,43.000000
std,NaN,4.521286,9.325907,31.695633,16.616920,16.794103,5.992874,16.047581,11.464592,8.399733,10.661641,9.248729,8.379523,11.991214,9.025362,12.918092,16.745674,4.104402

In [26]:
import os

In [27]:
excel_files = [file for file in os.listdir("./") if file.endswith(".xlsx")]
excel_files

['2000_NO2_1g.xlsx',
 '2000_PM10_24g.xlsx',
 '2000_SO2_24g.xlsx',
 '2000_O3_1g.xlsx',
 '2000_NOx_1g.xlsx',
 '2000_NO2_24g.xlsx']

# Rodzaj danych 3

In [28]:
dni = "3"
kod_stacji = "17160"
url_path_3 = f"https://powietrze.gios.gov.pl/pjp/current/station_details/table/{kod_stacji}/{dni}/0"
url_path_3

'https://powietrze.gios.gov.pl/pjp/current/station_details/table/17160/3/0'

In [29]:
df_list_3 = pd.read_html(url_path_3)

In [30]:
df_3 = df_list_3[0].copy()

In [31]:
df_3 = df_3.iloc[:, :-1]

In [32]:
df_3.columns = ('Czas', 'godziny')

ValueError: Length mismatch: Expected axis has 7 elements, new values have 2 elements

In [33]:
df_3.rename(columns={df_3.columns[0]: ('Czas', 'godziny')}, inplace=True)  # to nie działa

In [34]:
new_col_names = ["_".join(col) for col in df_3.columns]

In [35]:
df_3.columns = new_col_names

In [36]:
def get_station_daily_data(station_key, dni):
    url_path = f"https://powietrze.gios.gov.pl/pjp/current/station_details/table/{station_key}/{dni}/0"
    df = pd.read_html(url_path)[0]
    df = df.iloc[:, :-1]
    df = df.iloc[:-3, :]


    new_col_names = ["_".join(col) for col in df.columns]
    df.columns = new_col_names

    df.insert(loc=0, column='station_key', value=station_key)

    df.rename(columns={df.columns[1]: 'data_godzina'}, inplace=True)

    return df

In [37]:
get_station_daily_data("17160", "3")

,station_key,data_godzina,PM10_µg/m3,"PM2,5_µg/m3",O3_µg/m3,NO2_µg/m3,SO2_µg/m3,C6H6_µg/m3
0,17160,"18.09.2025, 01:00",NaN,NaN,NaN,NaN,NaN,NaN
1,17160,"18.09.2025, 02:00",NaN,NaN,NaN,NaN,NaN,NaN
2,17160,"18.09.2025, 03:00",NaN,NaN,NaN,NaN,NaN,NaN
3,17160,"18.09.2025, 04:00",NaN,NaN,NaN,NaN,NaN,NaN
4,17160,"18.09.2025, 05:00",NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
67,17160,"20.09.2025, 20:00",NaN,NaN,NaN,NaN,NaN,NaN
68,17160,"20.09.2025, 21:00",NaN,NaN,NaN,NaN,NaN,NaN
69,17160,"20.09.2025, 22:00",NaN,NaN,NaN,NaN,NaN,NaN
70,17160,"20.09.2025, 23:00",NaN,NaN,NaN,NaN,NaN,NaN
71,17160,"21.09.2025, 00:00",NaN,NaN,NaN,NaN,NaN,NaN

### Zadanie dokonać czyszczenia tej tabeli: typ kolumn, nazwy kolumn

# Rodzaj danych 4

specyfikacja: https://powietrze.gios.gov.pl/pjp/content/api

In [38]:
url_path_stations = "https://api.gios.gov.pl/pjp-api/rest/station/findAll"

In [39]:
df_stations = pd.read_json(url_path_stations)

In [40]:
df_stations

,id,stationName,gegrLat,gegrLon,city,addressStreet
0,11,Czerniawa,50.912475,15.312190,"{'id': 142, 'name': 'Czerniawa', 'commune': {'...",ul. Strażacka 7
1,16,"Dzierżoniów, ul. Piłsudskiego",50.732817,16.648050,"{'id': 198, 'name': 'Dzierżoniów', 'commune': ...",ul. Piłsudskiego 26
2,38,"Kłodzko, ul. Szkolna",50.433493,16.653660,"{'id': 368, 'name': 'Kłodzko', 'commune': {'co...",ul. Szkolna 8
3,52,"Legnica, al. Rzeczypospolitej",51.204503,16.180513,"{'id': 453, 'name': 'Legnica', 'commune': {'co...",al. Rzeczypospolitej 10/12
4,114,"Wrocław, ul. Bartnicza",51.115933,17.141125,"{'id': 1064, 'name': 'Wrocław', 'commune': {'c...",ul. Bartnicza
...,...,...,...,...,...,...
206,16894,"Nowy Targ, al. Tysiąclecia",49.476675,20.034878,"{'id': 626, 'name': 'Nowy Targ', 'commune': {'...",al. Tysiąclecia
207,20387,"Nysa, ul. Rodziewiczówny 1",50.460992,17.331499,"{'id': 628, 'name': 'Nysa', 'commune': {'commu...",ul. Rodziewiczówny 1
208,10817,"Złockie, szkoła podstawowa",49.374147,20.879581,"{'id': 2180, 'name': 'Złockie', 'commune': {'c...",Złockie 79
209,11301,"Olkusz, ul. Cegielniana",50.284000,19.564044,"{'id': 638, 'name': 'Olkusz', 'commune': {'com...",Cegielniana
210,16497,"Kielce, ul. Jurajska",50.887606,20.579965,"{'id': 360, 'name': 'Kielce', 'commune': {'com...",ul. Jurajska 7

In [41]:
df_expand_json = pd.json_normalize(df_stations['city'])

In [42]:
df_expand_json.rename(columns={'id': 'city_id'}, inplace=True)

In [43]:
df_stations = pd.concat((df_stations.drop(columns='city'), df_expand_json), axis=1)

In [44]:
df_stations

,id,stationName,gegrLat,gegrLon,addressStreet,city_id,name,commune.communeName,commune.districtName,commune.provinceName
0,11,Czerniawa,50.912475,15.312190,ul. Strażacka 7,142,Czerniawa,Świeradów-Zdrój,lubański,DOLNOŚLĄSKIE
1,16,"Dzierżoniów, ul. Piłsudskiego",50.732817,16.648050,ul. Piłsudskiego 26,198,Dzierżoniów,Dzierżoniów,dzierżoniowski,DOLNOŚLĄSKIE
2,38,"Kłodzko, ul. Szkolna",50.433493,16.653660,ul. Szkolna 8,368,Kłodzko,Kłodzko,kłodzki,DOLNOŚLĄSKIE
3,52,"Legnica, al. Rzeczypospolitej",51.204503,16.180513,al. Rzeczypospolitej 10/12,453,Legnica,Legnica,Legnica,DOLNOŚLĄSKIE
4,114,"Wrocław, ul. Bartnicza",51.115933,17.141125,ul. Bartnicza,1064,Wrocław,Wrocław,Wrocław,DOLNOŚLĄSKIE
...,...,...,...,...,...,...,...,...,...,...
206,16894,"Nowy Targ, al. Tysiąclecia",49.476675,20.034878,al. Tysiąclecia,626,Nowy Targ,Nowy Targ,nowotarski,MAŁOPOLSKIE
207,20387,"Nysa, ul. Rodziewiczówny 1",50.460992,17.331499,ul. Rodziewiczówny 1,628,Nysa,Nysa,nyski,OPOLSKIE
208,10817,"Złockie, szkoła podstawowa",49.374147,20.879581,Złockie 79,2180,Złockie,Muszyna,nowosądecki,MAŁOPOLSKIE
209,11301,"Olkusz, ul. Cegielniana",50.284000,19.564044,Cegielniana,638,Olkusz,Olkusz,olkuski,MAŁOPOLSKIE
210,16497,"Kielce, ul. Jurajska",50.887606,20.579965,ul. Jurajska 7,360,Kielce,Kielce,Kielce,ŚWIĘTOKRZYSKIE

In [45]:
url_sensors = "https://api.gios.gov.pl/pjp-api/rest/station/sensors/10934"  #  Co konkretnie jest mierzone w stacji 10934

In [46]:
df_sensors = pd.read_json(url_sensors)

In [47]:
df_sensors = pd.concat((df_sensors, pd.json_normalize(df_sensors['param'])), axis=1)

In [48]:
df_sensors.drop(columns='param', inplace=True)

In [49]:
df_sensors

      id  stationId             paramName paramFormula paramCode  idParam
0  29522      10934  pył zawieszony PM2.5        PM2.5     PM2.5       69
1  29523      10934   pył zawieszony PM10         PM10      PM10        3

# Rodzaj danych 5

## Tablica na stronie html

In [50]:
url_path_5 = "https://powietrze.gios.gov.pl/pjp/content/contact"

In [51]:
df_5 = pd.read_html(url_path_5)[0]

In [52]:
df_5

,RWMÅ,Naczelnik,Adres,Telefon,e-mail
0,Regionalny WydziaÅ Monitoringu Årodowiska w ...,Honorata Kujawa-Åobaczewska,ul. M. Piotrowskiego 7-9 85-098 Bydgoszcz,"(22) 574 27 04, 539 140 697",rwmsbydgoszcz@gios.gov.pl
1,Regionalny WydziaÅ Monitoringu Årodowiska w ...,Ryszard Góralczyk,"ul. Westerplatte 18, 31-033 Kraków","(12) 312 52 09 wew. 10, 539 140 696",rwmskrakow@gios.gov.pl
2,Regionalny WydziaÅ Monitoringu Årodowiska w ...,BartÅomiej ÅwiÄ tczak,"ul. Lipowa 16, 90-743 ÅódÅº","(42) 632 15 20, 539 141 238",rwmslodz@gios.gov.pl
3,Regionalny WydziaÅ Monitoringu Årodowiska w ...,Tomasz KoÅakowski,"ul. Abrahama 1A/lok. 4.12, 80-307 GdaÅsk",512 660 403,rwmsgdansk@gios.gov.pl
4,Regionalny WydziaÅ Monitoringu Årodowiska w ...,Andrzej SzczygieÅ,"ul. Konstantego Damrota 16, 40-022 Katowice",789 317 846,rwmskatowice@gios.gov.pl
5,Regionalny WydziaÅ Monitoringu Årodowiska w ...,Joanna JÄdras,"al. IX Wieków Kielc 3, 25-516 Kielce","(41) 342 14 96, 539 141 251",rwmskielce@gios.gov.pl
6,Regionalny WydziaÅ Monitoringu Årodowiska w ...,Magdalena Mencel,"ul. Czarna Rola 4, 61-625 PoznaÅ","(61) 827 05 03, 605 188 031",rwmspoznan@gios.gov.pl
7,Regionalny WydziaÅ Monitoringu Årodowiska w ...,MichaÅ Solis,"ul. Obywatelska 13, 20-092 Lublin","(22) 817 97 00, 539 141 468",rwmslublin@gios.gov.pl
8,Regionalny WydziaÅ Monitoringu Årodowiska w ...,Renata JaroÅ-WarszyÅska,"ul. Gen.M. Langiewicza 26, 35-101 Rzeszów","(22) 817 96 86, 539 140 671",rwmsrzeszow@gios.gov.pl
9,Regionalny WydziaÅ Monitoringu Årodowiska w ...,Dominik PolesiÅski,"ul. CioÅkowskiego 2/3, 15-264 BiaÅystok",539 140 705,rwmsbialystok@gios.gov.pl
10,Regionalny WydziaÅ Monitoringu Årodowiska w ...,Tomasz Zalewski,"ul. ks. WacÅawa OsiÅskiego 12/13, 10-011 Ol...","(89) 612 34 59, 539 141 252",rwmsolsztyn@gios.gov.pl
11,Regionalny WydziaÅ Monitoringu Årodowiska w ...,PrzemysÅaw Susek,"ul. Siemiradzkiego 19, 65-231 Zielona Góra","(68) 454 84 52, 539 140 670",rwmszielonagora@gios.gov.pl
12,Regionalny WydziaÅ Monitoringu Årodowiska we...,ÅwiÄtosÅawa Å»yniewicz,"ul. CheÅmoÅskiego 14, 51-630 WrocÅaw","(71) 327 30 49, 539 140 675",rwmswroclaw@gios.gov.pl
13,Regionalny WydziaÅ Monitoringu Årodowiska w ...,Barbara BaraÅska,"ul. Nysy ÅuÅ¼yckiej 42, 45-035 Opole","(22) 817 96 81, 539 140 677",rwmsopole@gios.gov.pl
14,Regionalny WydziaÅ Monitoringu Årodowiska w ...,Anna Bakierowska,"ul. Niemcewicza 26 pok.516, 71-520 Szczecin","(91) 443 62 11, 539 140 673",rwmsszczecin@gios.gov.pl

In [53]:
df_5.to_excel("dane_adresowe_rwms.xlsx", index=False)

## Tekst na stronie html - wyrażenia regularne - https://pythex.org/
https://powietrze.gios.gov.pl/pjp/content/contact

In [54]:
text = '''
Główny Inspektor Ochrony Środowiska
Joanna Piekutowska
Sekretariat:
tel. 22 36 92 209
e-mail: sekretariatgios@gios.gov.pl



I Zastępca Głównego Inspektora Ochrony Środowiska
Anna Dębowiec
Sekretariat:
tel. 22 36 92 567
e-mail: sekretariatzgios@gios.gov.pl


II Zastępca Głównego Inspektora Ochrony Środowiska
Alicja Żelichowska
Sekretariat:
tel. 22 36 92 567
e-mail: sekretariatzgios@gios.gov.pl


Dyrektor Generalny Głównego Inspektoratu Ochrony Środowiska
Damian Jakubik
Sekretariat:
tel. 22 36 92 630
e-mail: sekretariatdg@gios.gov.pl
'''

In [55]:
import re

In [56]:
re_phone = r'(\d{2} \d{2} \d{2} \d{3})'

In [57]:
re_stanowisko = r'(.+Ochrony Środowiska)'

In [58]:
re_imie_nazwisko = r'Ochrony Środowiska\n(.+ .+)\n'

In [59]:
re_email = r'e-mail: (.+@.+)'

In [60]:
re.findall(re_email, text)

['sekretariatgios@gios.gov.pl',
 'sekretariatzgios@gios.gov.pl',
 'sekretariatzgios@gios.gov.pl',
 'sekretariatdg@gios.gov.pl']

In [61]:
re_imie_nazwisko_wer2 = r'\n(\S+ \S+)\n\w'

In [62]:
data_dict = {"imie i nazwisko": re.findall(re_imie_nazwisko,text),
             "email": re.findall(re_email, text),
             "stanowisko": re.findall(re_stanowisko,text),
             "phone": re.findall(re_phone,text)
             }

In [63]:
df_contacts = pd.DataFrame(data_dict)  # zadanie: utworzyc dataframe z kolumnami: stanowisko, imie_nazwisko, email, telefon

In [64]:
df_contacts

,imie i nazwisko,email,stanowisko,phone
0,Joanna Piekutowska,sekretariatgios@gios.gov.pl,Główny Inspektor Ochrony Środowiska,22 36 92 209
1,Anna Dębowiec,sekretariatzgios@gios.gov.pl,I Zastępca Głównego Inspektora Ochrony Środowiska,22 36 92 567
2,Alicja Żelichowska,sekretariatzgios@gios.gov.pl,II Zastępca Głównego Inspektora Ochrony Środow...,22 36 92 567
3,Damian Jakubik,sekretariatdg@gios.gov.pl,Dyrektor Generalny Głównego Inspektoratu Ochro...,22 36 92 630

Skorzystanie z entity extraction: https://spacy.io/

In [65]:
# pip install -U spacy
# python -m spacy download en_core_web_sm
import spacy

# Load English tokenizer, tagger, parser and NER
nlp = spacy.load("en_core_web_sm")

# Process whole documents
text = ("When Sebastian Thrun started working on self-driving cars at "
        "Google in 2007, few people outside of the company took him "
        "seriously. “I can tell you very senior CEOs of major American "
        "car companies would shake my hand and turn away because I wasn’t "
        "worth talking to,” said Thrun, in an interview with Recode earlier "
        "this week.")
doc = nlp(text)

# Analyze syntax
print("Noun phrases:", [chunk.text for chunk in doc.noun_chunks])
print("Verbs:", [token.lemma_ for token in doc if token.pos_ == "VERB"])

# Find named entities, phrases and concepts
for entity in doc.ents:
    print(entity.text, entity.label_)

Noun phrases: ['Sebastian Thrun', 'self-driving cars', 'Google', 'few people', 'the company', 'him', 'I', 'you', 'very senior CEOs', 'major American car companies', 'my hand', 'I', 'Thrun', 'an interview', 'Recode']
Verbs: ['start', 'work', 'drive', 'take', 'tell', 'shake', 'turn', 'talk', 'say']
Sebastian Thrun PERSON
Google ORG
2007 DATE
American NORP
Thrun GPE
Recode ORG
earlier this week DATE

# Zapisywanie danych do bazy danych

In [66]:
import sqlite3

In [67]:
db = sqlite3.connect("dane_zanieczyszczenia.db")

In [68]:
df_contacts.to_sql("dane_kontaktowe", db, if_exists="replace", index=False)

4

In [69]:
pd.read_sql('select * from dane_kontaktowe where email = "sekretariatgios@gios.gov.pl"', db)

,imie i nazwisko,email,stanowisko,phone
0,Joanna Piekutowska,sekretariatgios@gios.gov.pl,Główny Inspektor Ochrony Środowiska,22 36 92 209

# Przeglądarka bazy danych: https://sqlitebrowser.org/

https://download.sqlitebrowser.org/DB.Browser.for.SQLite-v3.13.1-win64.msi

## ładowanie danych godzinowych dla wybranej stacji

In [70]:
def load_station_daily_data(db, station_key, dni, if_exist="append"):
  df = get_station_daily_data(station_key, dni)
  df.to_sql("pomiary_godzinowe", db, if_exists=if_exist, index=False)

In [71]:
load_station_daily_data(db, "17160", "3", "replace")  # za pierwszym razem tworzę tabelę

In [72]:
load_station_daily_data(db, "9913", "3", "append")  #  za każdym kolejnum razem dodaję wiersze do tabeli

In [73]:
load_station_daily_data(db, "562", "3", "append")

In [74]:
df = pd.read_sql('select * from pomiary_godzinowe', db)

In [75]:
df.describe()

       PM10_µg/m3  PM2,5_µg/m3    O3_µg/m3  NO2_µg/m3  SO2_µg/m3
count   58.000000    58.000000   58.000000  58.000000  58.000000
mean    72.844828    58.293103  379.655172  32.913793   6.017241
std     35.144215    26.889644  198.318506  17.228378   2.958730
min      4.000000     4.000000   17.000000   3.000000   1.000000
25%     52.250000    37.250000  286.750000  21.000000   5.000000
50%     83.500000    61.000000  349.500000  33.000000   5.000000
75%     99.000000    83.750000  481.750000  44.500000   6.000000
max    121.000000    96.000000  874.000000  71.000000  19.000000

In [76]:
df_groupby = df.groupby(by='station_key')

In [77]:
for key, df in df_groupby:  #  iteracja po groupby
  print(df)

   station_key       data_godzina  PM10_µg/m3  PM2,5_µg/m3  O3_µg/m3  \
0        17160  18.09.2025, 01:00         NaN          NaN       NaN
1        17160  18.09.2025, 02:00         NaN          NaN       NaN
2        17160  18.09.2025, 03:00         NaN          NaN       NaN
3        17160  18.09.2025, 04:00         NaN          NaN       NaN
4        17160  18.09.2025, 05:00         NaN          NaN       NaN
..         ...                ...         ...          ...       ...
67       17160  20.09.2025, 20:00         NaN          NaN       NaN
68       17160  20.09.2025, 21:00         NaN          NaN       NaN
69       17160  20.09.2025, 22:00         NaN          NaN       NaN
70       17160  20.09.2025, 23:00         NaN          NaN       NaN
71       17160  21.09.2025, 00:00         NaN          NaN       NaN

    NO2_µg/m3  SO2_µg/m3 C6H6_µg/m3
0         NaN        NaN       None
1         NaN        NaN       None
2         NaN        NaN       None
3         NaN        NaN       None
4         NaN        NaN       None
..        ...        ...        ...
67        NaN        NaN       None
68        NaN        NaN       None
69        NaN        NaN       None
70        NaN        NaN       None
71        NaN        NaN       None

[72 rows x 8 columns]
    station_key       data_godzina  PM10_µg/m3  PM2,5_µg/m3  O3_µg/m3  \
144         562  18.09.2025, 01:00         NaN          NaN       NaN
145         562  18.09.2025, 02:00         NaN          NaN       NaN
146         562  18.09.2025, 03:00         NaN          NaN       NaN
147         562  18.09.2025, 04:00         NaN          NaN       NaN
148         562  18.09.2025, 05:00         NaN          NaN       NaN
..          ...                ...         ...          ...       ...
211         562  20.09.2025, 20:00         NaN          NaN       NaN
212         562  20.09.2025, 21:00         NaN          NaN       NaN
213         562  20.09.2025, 22:00         NaN          NaN       NaN
214         562  20.09.2025, 23:00         NaN          NaN       NaN
215         562  21.09.2025, 00:00         NaN          NaN       NaN

     NO2_µg/m3  SO2_µg/m3 C6H6_µg/m3
144        NaN        NaN       None
145        NaN        NaN       None
146        NaN        NaN       None
147        NaN        NaN       None
148        NaN        NaN       None
..         ...        ...        ...
211        NaN        NaN       None
212        NaN        NaN       None
213        NaN        NaN       None
214        NaN        NaN       None
215        NaN        NaN       None

[72 rows x 8 columns]
    station_key       data_godzina  PM10_µg/m3  PM2,5_µg/m3  O3_µg/m3  \
72         9913  18.09.2025, 01:00        63.0         47.0     435.0
73         9913  18.09.2025, 02:00        61.0         45.0     419.0
74         9913  18.09.2025, 03:00        55.0          4.0     418.0
75         9913  18.09.2025, 04:00        67.0         51.0     372.0
76         9913  18.09.2025, 05:00        75.0         57.0     354.0
..          ...                ...         ...          ...       ...
139        9913  20.09.2025, 20:00         NaN          NaN       NaN
140        9913  20.09.2025, 21:00         NaN          NaN       NaN
141        9913  20.09.2025, 22:00         NaN          NaN       NaN
142        9913  20.09.2025, 23:00         NaN          NaN       NaN
143        9913  21.09.2025, 00:00         NaN          NaN       NaN

     NO2_µg/m3  SO2_µg/m3 C6H6_µg/m3
72        34.0        8.0       None
73        33.0        6.0       None
74        24.0        5.0       None
75        28.0        6.0       None
76        32.0        7.0       None
..         ...        ...        ...
139        NaN        NaN       None
140        NaN        NaN       None
141        NaN        NaN       None
142        NaN        NaN       None
143        NaN        NaN       None

[72 rows x 8 columns]

In [78]:
df_groupby.get_group('17160')  # tak dostaje się do konkretnej grupy

,station_key,data_godzina,PM10_µg/m3,"PM2,5_µg/m3",O3_µg/m3,NO2_µg/m3,SO2_µg/m3,C6H6_µg/m3
0,17160,"18.09.2025, 01:00",NaN,NaN,NaN,NaN,NaN,None
1,17160,"18.09.2025, 02:00",NaN,NaN,NaN,NaN,NaN,None
2,17160,"18.09.2025, 03:00",NaN,NaN,NaN,NaN,NaN,None
3,17160,"18.09.2025, 04:00",NaN,NaN,NaN,NaN,NaN,None
4,17160,"18.09.2025, 05:00",NaN,NaN,NaN,NaN,NaN,None
...,...,...,...,...,...,...,...,...
67,17160,"20.09.2025, 20:00",NaN,NaN,NaN,NaN,NaN,None
68,17160,"20.09.2025, 21:00",NaN,NaN,NaN,NaN,NaN,None
69,17160,"20.09.2025, 22:00",NaN,NaN,NaN,NaN,NaN,None
70,17160,"20.09.2025, 23:00",NaN,NaN,NaN,NaN,NaN,None
71,17160,"21.09.2025, 00:00",NaN,NaN,NaN,NaN,NaN,None

In [79]:
df_groupby.describe().T  # tak liczę statystyki opisowe dla każdej grupy

station_key        17160  562        9913
PM10_µg/m3  count    0.0  0.0   58.000000
            mean     NaN  NaN   72.844828
            std      NaN  NaN   35.144215
            min      NaN  NaN    4.000000
            25%      NaN  NaN   52.250000
            50%      NaN  NaN   83.500000
            75%      NaN  NaN   99.000000
            max      NaN  NaN  121.000000
PM2,5_µg/m3 count    0.0  0.0   58.000000
            mean     NaN  NaN   58.293103
            std      NaN  NaN   26.889644
            min      NaN  NaN    4.000000
            25%      NaN  NaN   37.250000
            50%      NaN  NaN   61.000000
            75%      NaN  NaN   83.750000
            max      NaN  NaN   96.000000
O3_µg/m3    count    0.0  0.0   58.000000
            mean     NaN  NaN  379.655172
            std      NaN  NaN  198.318506
            min      NaN  NaN   17.000000
            25%      NaN  NaN  286.750000
            50%      NaN  NaN  349.500000
            75%      NaN  NaN  481.750000
            max      NaN  NaN  874.000000
NO2_µg/m3   count    0.0  0.0   58.000000
            mean     NaN  NaN   32.913793
            std      NaN  NaN   17.228378
            min      NaN  NaN    3.000000
            25%      NaN  NaN   21.000000
            50%      NaN  NaN   33.000000
            75%      NaN  NaN   44.500000
            max      NaN  NaN   71.000000
SO2_µg/m3   count    0.0  0.0   58.000000
            mean     NaN  NaN    6.017241
            std      NaN  NaN    2.958730
            min      NaN  NaN    1.000000
            25%      NaN  NaN    5.000000
            50%      NaN  NaN    5.000000
            75%      NaN  NaN    6.000000
            max      NaN  NaN   19.000000

# Rodzaj 6 - pdf: https://pypi.org/project/tabula-py/

## Przykładowy notebook: https://colab.research.google.com/github/chezou/tabula-py/blob/master/examples/tabula_example.ipynb

Przykład danych: kody pocztowe pdf
https://www.poczta-polska.pl/wp-content/uploads/2024/05/oficjalny-spis-pna-2024.pdf

In [80]:
url_path_6 = "https://powietrze.gios.gov.pl/pjp/documents/download/114807"

In [81]:
!pip install tabula-py

Collecting tabula-py
  Downloading tabula_py-2.10.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.12/dist-packages (from tabula-py) (2.2.2)
Requirement already satisfied: numpy>1.24.4 in /usr/local/lib/python3.12/dist-packages (from tabula-py) (2.0.2)
Requirement already satisfied: distro in /usr/local/lib/python3.12/dist-packages (from tabula-py) (1.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->tabula-py) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->tabula-py) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->tabula-py) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->tabula-py) (1.17.0)
Downloading tabula_py-2.10.0-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 89.7 MB/s eta 0:00:00
Installing collected packages: tabula-py
Successfully installed tabula-py-2.10.0

In [82]:
import tabula

tabula.environment_info()

Python version:
    3.12.11 (main, Jun  4 2025, 08:56:18) [GCC 11.4.0]
Java version:
    openjdk version "11.0.28" 2025-07-15
OpenJDK Runtime Environment (build 11.0.28+6-post-Ubuntu-1ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.28+6-post-Ubuntu-1ubuntu122.04.1, mixed mode, sharing)
tabula-py version: 2.10.0
platform: Linux-6.1.123+-x86_64-with-glibc2.35
uname:
    uname_result(system='Linux', node='1d4a112a89d6', release='6.1.123+', version='#1 SMP PREEMPT_DYNAMIC Sun Mar 30 16:01:29 UTC 2025', machine='x86_64')
linux_distribution: ('Ubuntu', '22.04', 'jammy')
mac_ver: ('', ('', '', ''), '')

In [83]:
pdf_path = url_path_6

dfs = tabula.read_pdf(pdf_path, stream=True, pages='all')
# read_pdf returns list of DataFrames
print(len(dfs))
dfs[0]

WARNING:tabula.backend:Failed to import jpype dependencies. Fallback to subprocess.
WARNING:tabula.backend:No module named 'jpype'
WARNING:tabula.backend:Got stderr: Sep 20, 2025 11:21:20 AM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider loadDiskCache
WARNING: New fonts found, font cache will be re-built
Sep 20, 2025 11:21:20 AM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
WARNING: Building on-disk font cache, this may take a while
Sep 20, 2025 11:21:20 AM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
WARNING: Finished building on-disk font cache, found 17 fonts
Sep 20, 2025 11:21:24 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'TimesNewRomanPSMT'
Sep 20, 2025 11:21:24 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'TimesNewRomanPSMT'
Sep 20, 2025 11:21:25 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'TimesNewRomanPSMT'
Sep 20, 2025 11:21:27 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'TimesNewRomanPSMT'
Sep 20, 2025 11:21:27 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'TimesNewRomanPSMT'
Sep 20, 2025 11:21:27 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'TimesNewRomanPSMT'
Sep 20, 2025 11:21:42 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'TimesNewRomanPSMT'
Sep 20, 2025 11:22:01 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'TimesNewRomanPSMT'
Sep 20, 2025 11:22:12 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'TimesNewRomanPSMT'
Sep 20, 2025 11:22:16 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'TimesNewRomanPSMT'
Sep 20, 2025 11:22:23 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'TimesNewRomanPSMT'
Sep 20, 2025 11:22:25 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans-Bold' for 'TimesNewRomanPS-BoldItalicMT'
Sep 20, 2025 11:22:26 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans-Bold' for 'TimesNewRomanPS-BoldItalicMT'
Sep 20, 2025 11:22:27 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'TimesNewRomanPSMT'

82

,Klasa,Poziom stężeń,Unnamed: 0,Unnamed: 1
0,NaN,NaN,NaN,Wymagane działania
1,strefy,zanieczyszczenia,NaN,NaN
2,NaN,nie przekracza,—,utrzymanie stężeń zanieczyszczenia poniżej poz...
3,A,poziomu,NaN,dążenie do utrzymania najlepszej jakość powiet...
4,NaN,dopuszczalnego2),NaN,ze zrównoważonym rozwojem.
5,NaN,NaN,—,określenie obszarów przekroczeń poziomów dopus...
6,NaN,NaN,—,opracowanie lub aktualizacja programu ochrony ...
7,NaN,NaN,NaN,integralną część stanowi plan działań krótkote...
8,NaN,NaN,NaN,osiągnięcia odpowiednich poziomów dopuszczalny...
9,NaN,NaN,NaN,w powietrzu; program powinien uwzględniać wyni...
10,NaN,powyżej poziomu,NaN,w przekroczeniach poziomów substancji w powiet...
11,C,dopuszczalnego2),NaN,grup źródeł emisji tych substancji i określeni...
12,NaN,NaN,NaN,"naprawczych, tak aby okresy, w których nie są ..."
13,NaN,NaN,NaN,"dopuszczalne, były jak najkrótsze,"
14,NaN,NaN,—,kontrolowanie stężeń zanieczyszczenia na obsza...
15,NaN,NaN,NaN,i prowadzenie działań mających na celu obniżen...
16,NaN,NaN,NaN,do poziomów dopuszczalnych.

In [84]:
len(dfs)

82